// Generated by scripts/gen-db-types.mjs — do not edit by hand.
// Filtered to uc_-prefixed objects; regenerate with: npm run gen:db-types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
	// Allows to automatically instantiate createClient with right options
	// instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
	__InternalSupabase: {
		PostgrestVersion: '12.0.1 (cd38da5)';
	};
	public: {
		Tables: {
			uc_admins: {
				Row: {
					created_at: string;
					user_id: string;
				};
				Insert: {
					created_at?: string;
					user_id: string;
				};
				Update: {
					created_at?: string;
					user_id?: string;
				};
				Relationships: [];
			};
			uc_announcements: {
				Row: {
					body: string;
					created_at: string;
					ends_at: string | null;
					id: string;
					link_label: string | null;
					link_url: string | null;
					photo: string | null;
					popup: boolean;
					popup_days: number;
					published: boolean;
					starts_at: string;
					title: string;
					updated_at: string;
				};
				Insert: {
					body: string;
					created_at?: string;
					ends_at?: string | null;
					id?: string;
					link_label?: string | null;
					link_url?: string | null;
					photo?: string | null;
					popup?: boolean;
					popup_days?: number;
					published?: boolean;
					starts_at?: string;
					title: string;
					updated_at?: string;
				};
				Update: {
					body?: string;
					created_at?: string;
					ends_at?: string | null;
					id?: string;
					link_label?: string | null;
					link_url?: string | null;
					photo?: string | null;
					popup?: boolean;
					popup_days?: number;
					published?: boolean;
					starts_at?: string;
					title?: string;
					updated_at?: string;
				};
				Relationships: [];
			};
			uc_form_submissions: {
				Row: {
					created_at: string;
					data: Json;
					form_name: string;
					id: string;
					is_read: boolean;
					photos: string[];
				};
				Insert: {
					created_at?: string;
					data?: Json;
					form_name: string;
					id?: string;
					is_read?: boolean;
					photos?: string[];
				};
				Update: {
					created_at?: string;
					data?: Json;
					form_name?: string;
					id?: string;
					is_read?: boolean;
					photos?: string[];
				};
				Relationships: [];
			};
			uc_gallery_items: {
				Row: {
					created_at: string;
					description: string;
					id: string;
					label: string;
					photo: string | null;
					service_slug: string | null;
					sort_order: number;
				};
				Insert: {
					created_at?: string;
					description: string;
					id?: string;
					label: string;
					photo?: string | null;
					service_slug?: string | null;
					sort_order?: number;
				};
				Update: {
					created_at?: string;
					description?: string;
					id?: string;
					label?: string;
					photo?: string | null;
					service_slug?: string | null;
					sort_order?: number;
				};
				Relationships: [];
			};
			uc_machines: {
				Row: {
					category_id: string;
					created_at: string;
					currency: string;
					description: string | null;
					id: string;
					machine_type: string;
					photos: string[];
					price: number | null;
					slug: string;
					specs: Json;
					status: string;
					title: string;
				};
				Insert: {
					category_id: string;
					created_at?: string;
					currency?: string;
					description?: string | null;
					id?: string;
					machine_type: string;
					photos?: string[];
					price?: number | null;
					slug: string;
					specs?: Json;
					status?: string;
					title: string;
				};
				Update: {
					category_id?: string;
					created_at?: string;
					currency?: string;
					description?: string | null;
					id?: string;
					machine_type?: string;
					photos?: string[];
					price?: number | null;
					slug?: string;
					specs?: Json;
					status?: string;
					title?: string;
				};
				Relationships: [
					{
						foreignKeyName: 'uc_machines_category_id_fkey';
						columns: ['category_id'];
						isOneToOne: false;
						referencedRelation: 'uc_sale_categories';
						referencedColumns: ['id'];
					}
				];
			};
			uc_references: {
				Row: {
					created_at: string;
					id: string;
					logo: string | null;
					name: string;
					sector: string | null;
					sort_order: number;
				};
				Insert: {
					created_at?: string;
					id?: string;
					logo?: string | null;
					name: string;
					sector?: string | null;
					sort_order?: number;
				};
				Update: {
					created_at?: string;
					id?: string;
					logo?: string | null;
					name?: string;
					sector?: string | null;
					sort_order?: number;
				};
				Relationships: [];
			};
			uc_sale_categories: {
				Row: {
					created_at: string;
					id: string;
					sort_order: number;
					title: string;
				};
				Insert: {
					created_at?: string;
					id?: string;
					sort_order?: number;
					title: string;
				};
				Update: {
					created_at?: string;
					id?: string;
					sort_order?: number;
					title?: string;
				};
				Relationships: [];
			};
			uc_stats: {
				Row: {
					created_at: string;
					id: string;
					label: string;
					sort_order: number;
					value: string;
				};
				Insert: {
					created_at?: string;
					id?: string;
					label: string;
					sort_order?: number;
					value: string;
				};
				Update: {
					created_at?: string;
					id?: string;
					label?: string;
					sort_order?: number;
					value?: string;
				};
				Relationships: [];
			};
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			uc_is_admin: { Args: never; Returns: boolean };
		};
		Enums: {
			[_ in never]: never;
		};
		CompositeTypes: {
			[_ in never]: never;
		};
	};
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
	DefaultSchemaTableNameOrOptions extends
		| keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends (DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
				DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
		: never) = never
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
			DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
			Row: infer R;
		}
		? R
		: never
	: DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
		? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
				Row: infer R;
			}
			? R
			: never
		: never;

export type TablesInsert<
	DefaultSchemaTableNameOrOptions extends
		keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
	TableName extends (DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
		: never) = never
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
			Insert: infer I;
		}
		? I
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
		? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
				Insert: infer I;
			}
			? I
			: never
		: never;

export type TablesUpdate<
	DefaultSchemaTableNameOrOptions extends
		keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
	TableName extends (DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
		: never) = never
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
			Update: infer U;
		}
		? U
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
		? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
				Update: infer U;
			}
			? U
			: never
		: never;

export type Enums<
	DefaultSchemaEnumNameOrOptions extends
		keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
	EnumName extends (DefaultSchemaEnumNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
		: never) = never
> = DefaultSchemaEnumNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
	: DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
		? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
		: never;

export type CompositeTypes<
	PublicCompositeTypeNameOrOptions extends
		keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
	CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
		: never) = never
> = PublicCompositeTypeNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
	: PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
		? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
		: never;

export const Constants = {
	public: {
		Enums: {}
	}
} as const;
